on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: npm install, make test-coverage
      run: |
        python3 -m pip install coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v2